spring:
  profiles:
    active: cr

  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/template/
    cache: false
    suffix: .html

server:
  port: 10368
  tomcat:
    uri-encoding: utf-8

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: link.ahsj.sqlserver.mapper
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #      #数据库大写下划线转换
      capital-mode: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    #关闭缓存
    cache-enabled: false
