spring:
  profiles:
    active: c9

  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/template/
    cache: false
    mode: HTML
    suffix: .html

server:
  port: 8093
  tomcat:
    uri-encoding: utf-8

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cingsoft.cloud.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: sqlserver2012
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql